### ISSUE TITLE
vmprof.com is down

### ISSUE THREAD

**Issue by CrazyPython** [vmprof/vmprof-server#22]
[It's down for everyone.](http://downforeveryoneorjustme.com/vmprof.com)

In the meantime, are there any alternative vmprof servers?

**Comment by planrich** [comment]
Sorry for the down time. I'll have to investigate when I get back to a real
keyboard. For now i just restartet the service!

**Comment by planrich** [comment]
The service is operating normal now. I will watch it more closely. To answer you question:
You can locally setup vmprof-server by going through the docs! All you need to specify is --web-url localhost when you invoke vmprof!
