### ISSUE TITLE
VMProf log: Server rejected profile. status: 500

### ISSUE THREAD

**Issue by elistevens** [vmprof/vmprof-server#23]
Not sure if this is the correct place to report issues with vmprof.com, apologies if not.

I've been getting the following repeatedly (8 to 8:30ish, Pacific time):
```
$ venv/dsb/bin/python -m vmprof --web raw2prep.py ...
...
Compiling and uploading to http://vmprof.com...
VMProf log: Server rejected profile. status: 500, msg: '<h1>Server Error (500)</h1>'
```
Not sure what else I can do to debug.

**Comment by planrich** [comment]
Yes you found the right place! Thanks for the report.

Though I could not verify that. It worked for a very small example. What version of vmprof are you using? 0.3.16?

I think that your command line string is too long. I get the same error when I have too many characters. Can you reduce that for now? Is there a reason why it is so long?

**Comment by elistevens** [comment]
I'm away from the computer now, but I did the pip install of vmprof earlier
this morning.

The long command line is because there are a lot of files to process, but I
can get away with an in-program glob for the time being.

Thanks!

**Comment by planrich** [comment]
Is it important to have the full string as part of the profile?

**Comment by elistevens** [comment]
Not for my use case. I'd be fine with having it truncated to the first N
characters.

**Comment by planrich** [comment]
This isssue has been open too long (sorry for that). The server now truncates the command line argument to 255 characters.

**Comment by elistevens** [comment]
Thanks!

**Comment by planrich** [comment]
I have deployed fc946c8
