### ISSUE TITLE
Removing two entries

### ISSUE THREAD

**Issue by bivald** [vmprof/vmprof-server#29]
I uploaded two performance executions on vmprof.com using my access token. I was naively under the impression that if I used my access token it would be private too me. Honestly I don't know why I thought so since it doesn't say that in the documentation. Sorry.

Would it be possible to remove id d4db0d7f-0a87-4203-a0a3-789d541ce30e and 1274d5cd-cd39-44be-b6ab-e9772833104d? 

Sorry for the trouble, it's a great tool 👍

**Comment by planrich** [comment]
Removed it.
